# Generated by Django 3.2.12 on 2024-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('B', 'Bird'), ('C', 'Cat'), ('D', 'Dog')], default='B', max_length=100),
        ),
    ]
