# Generated by Django 5.0.1 on 2024-01-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('B', 'Bird'), ('C', 'Cat'), ('D', 'Dog'), ('F', 'Ferret'), ('H', 'Hamster'), ('G', 'Guinea Pig'), ('L', 'Lizard'), ('R', 'Rabbit')], default='B', max_length=100),
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='checkin date')),
                ('room', models.CharField(choices=[(1, 'Room 1'), (2, 'Room 2'), (3, 'Room 3'), (4, 'Room 4'), (5, 'Room 5')], default=1, max_length=100)),
                ('reason', models.TextField(max_length=250)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
