# Generated by Django 5.0.1 on 2024-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pet_species_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='room',
            field=models.CharField(choices=[('1', 'Room 1'), ('2', 'Room 2'), ('3', 'Room 3'), ('4', 'Room 4'), ('5', 'Room 5')], default='1', max_length=100),
        ),
    ]
