# Generated by Django 5.0.1 on 2024-01-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='rxs',
            field=models.ManyToManyField(to='main_app.rx'),
        ),
    ]
