# Generated by Django 5.0.1 on 2024-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_pet_rxs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='rxs',
        ),
        migrations.AddField(
            model_name='checkin',
            name='rxs',
            field=models.ManyToManyField(to='main_app.rx'),
        ),
    ]
