# Generated by Django 5.0.1 on 2024-01-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_pet_veterinarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='notes',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
