# Generated by Django 5.0.1 on 2024-01-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_checkin_notes'),
        ('main_app', '0011_photo'),
    ]

    operations = [
    ]
